# yml 文件格式特征：1 下一级缩进2字符。2 冒号后 需空格隔开值
spring:
  application:
    name: resilience4j-2
server:
  port: 5000
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka
resilience4j:
  retry:
    retry-aspect-order: 399 # 表示retry的优先级，值越小，优先级越高
    backends:
      retryA:
        maxRetryAttempts: 5 # 重试次数
        waitDuration: 500  # 重试等待时间
        exponentialBackoffMultiplier: 1.1 # 间隔乘数
        retryExceptions:
          - java.lang.RuntimeException
  circuitbreaker:
    instances:
      cbA:
        ringBufferSizeInClosedState: 5
        ringBufferSizeInHalfOpenState: 3
        waitInterval: 5000
        recordExceptions:
          - org.springframework.web.client.HttpServerErrorException
    circuit-breaker-aspect-order: 398
